# -*- coding: utf-8 -*-
"""
Created on Sat Dec 11 13:56:41 2021

@author: Pavel
"""
import Bz_Field as Bz
import COV
from DEAP_Field_refactored import Genetic
import numpy as np
import matplotlib.pyplot as plt
import Plot
import Resistance
import tomli
from turns_splitter import split
import streamlit as st
import macros

with open('parameters.toml', 'rb') as toml:
    parameters = tomli.load(toml)

GA = Genetic(parameters)
GA.preparation()

flat_radii_array = GA.execution()
radii_array = split(flat_radii_array, GA.freq)
Magnetic_field = GA.determine_Bz(GA.hall_of_fame[0])
final_COV = GA.determine_COV(Magnetic_field)
GA.show()

if GA.figure == 'Circular':
    length = Resistance.length_circular_coils(coils=radii_array)
    coil_pic = Plot.plot_coil(a_max=GA.a_max, spacing=GA.spacing, R=flat_radii_array)
    field_pic_3d = Plot.plot_3d(Bz=Magnetic_field,
                                height=GA.height, a_max=GA.a_max,
                                spacing=GA.spacing, cp=GA.cp)
    macros = macros.create_circular_macros(radii_array)
elif GA.figure == 'Rectangle':
    length = Resistance.length_square_coils(coils=radii_array)
    coil_pic = Plot.plot_square_coil(m_max=GA.X_side, n_max=GA.Y_side, spacing=GA.spacing, R=flat_radii_array)
    field_pic_3d = Plot.plot_3d(Bz=Magnetic_field,
                                height=GA.height, a_max=max(GA.X_side, GA.Y_side),
                                spacing=GA.spacing, cp=GA.cp)
    macros = macros.create_rectangular_macros(radii_array)
elif GA.figure == 'Piecewise':
    l = []
    for i in range(len(GA.coords)):
        l.append(np.sqrt((GA.coords[i][0]) ** 2 + (GA.coords[i][1]) ** 2))
    calc_radius = max(l) * GA.spacing

    length = Resistance.length_piecewise_linear_coils(coils=radii_array)
    coil_pic = Plot.plot_piecewise_linear_coil(coords_max=GA.coords, spacing=GA.spacing, R=flat_radii_array)
    field_pic_3d = Plot.plot_3d(Bz=Magnetic_field,
                                height=GA.height, a_max=calc_radius,
                                spacing=GA.spacing, cp=GA.cp)
    # macros = macros.(radii_array)

resistance = Resistance.resistance_contour(l=length, material=GA.material, d=GA.minimal_gap, nu=GA.freq)


st.download_button(label="Download a CST macros for your coil",
                   file_name="macros.mcs", data=macros, mime="text/mcs")
st.write(f'The COV if the magnetic field generated by your coil is {100*final_COV:.0f}%.')
st.write(f'These are the proportion coefficients (radii):')
st.write(radii_array)
st.write(f'This is the resistance of your coil (Ohm):')
st.write(resistance)
st.write(f'This is the total length of your coil (m):')
st.write(sum(length))
st.pyplot(coil_pic, dpi=1000)
# st.pyplot(field_pic_2d, dpi=1000)
st.pyplot(field_pic_3d, dpi=1000)

